version: 2
jobs:
  build:
    working_directory: ~/tmp 
    docker: 
      - image: circleci/node:7
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - store_test_results:
          path: ~/tmp/test-results
      - store_artifacts:
          path: ~/code/test-results
          destination: prefix
test:
  override:
    - mocha test --reporter mocha-junit-reporter:
        environment:
          MOCHA_FILE: $CIRCLE_TEST_REPORTS/junit/test-results.xml