version: 2
jobs:
  build:
    working_directory: ~/tmp 
    docker: 
      - image: circleci/node:7
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - store_test_results:
          path: test-results.xml
deployment:
  production:
    branch: master
    commands:
      - firebase deploy --token=1/TTEYWThg-x-xK8cCKJcEZvLyh9L6M_JdGq4MKjTkhL8 --non-interactive